-- generated by dbdsgnr.appspot.com

CREATE TABLE `Station` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60),
  PRIMARY KEY  (`id`)
);

CREATE TABLE `Train` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` INT,
  `count` INT,
  PRIMARY KEY  (`id`)
);

CREATE TABLE `Passenger` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60),
  `second_name` VARCHAR(60),
  `date` DATE,
  PRIMARY KEY  (`id`)
);

CREATE TABLE `Ticket` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `train_id` INT,
  `user_id` INT,
  PRIMARY KEY  (`id`)
);

CREATE TABLE `Route` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `train_id` INT,
  PRIMARY KEY  (`id`)
);

CREATE TABLE `Routing_stations` (
  `route_id` INT,
  `station_id` INT,
  `route` INT
);

CREATE TABLE `User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(40),
  `password` VARCHAR(40),
  `access` INT,
  PRIMARY KEY  (`id`)
);




ALTER TABLE `Ticket` ADD CONSTRAINT `Ticket_fk1` FOREIGN KEY (`train_id`) REFERENCES Train(`id`);
ALTER TABLE `Ticket` ADD CONSTRAINT `Ticket_fk2` FOREIGN KEY (`user_id`) REFERENCES Passenger(`id`);
ALTER TABLE `Route` ADD CONSTRAINT `Route_fk1` FOREIGN KEY (`train_id`) REFERENCES Train(`id`);
ALTER TABLE `Routing_stations` ADD CONSTRAINT `Routing_stations_fk1` FOREIGN KEY (`route_id`) REFERENCES Route(`id`);
ALTER TABLE `Routing_stations` ADD CONSTRAINT `Routing_stations_fk2` FOREIGN KEY (`station_id`) REFERENCES Station(`id`);
ALTER TABLE `Routing_stations` ADD CONSTRAINT `Routing_stations_fk3` FOREIGN KEY (`route`) REFERENCES Route(`id`);